### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by Vikram12301** [wwfish/tflite-model-maker#1]
I ran the below code after running the code in Tflite_Model_Maker_Python_3_9.ipynb
```
!pip install -q tflite-model-maker
!pip install -q tflite-support
```
But, I am getting an error during import
```
from tflite_model_maker.config import ExportFormat, QuantizationConfig
```
ImportError: Python version mismatch: module was compiled for Python 3.9, but the interpreter version is incompatible: 3.10.12 (main, Jun  7 2023, 12:45:35) [GCC 9.4.0].

**Comment by wwfish** [comment]
Everytime you run a command you must activate the conda environment to use Python 3.9, for instance:

`%%shell
eval "$(conda shell.bash hook)"
conda activate myenv`

If you code block 7 of the [Running the Colab Workbook](https://github.com/wwfish/tflite-model-maker-workaround#running-the-colab-workbook) section you should be able to install tflite-model-maker and tflite-support with pip.

**Comment by Vikram12301** [comment]
After I change the paths of the dataset, it just froze like below
![eror](https://github.com/wwfish/tflite-model-maker-workaround/assets/62374169/df99b866-6d3e-4f10-8b68-247287a3a503)

**Comment by wwfish** [comment]
Can you confirm whether the file structure of your images and xmls files matches that of your data paths in the dataloader section of the train.py file?

Images and xml files in the sample data are loaded through the folder `android_figurine/train` and `android_figurine/validate`

Does this part of the your train.py reflect the same paths?

```
train_data = object_detector.DataLoader.from_pascal_voc(
    'android_figurine/train',
    'android_figurine/train',
    ['android', 'pig_android']
)

val_data = object_detector.DataLoader.from_pascal_voc(
    'android_figurine/validate',
    'android_figurine/validate',
    ['android', 'pig_android']
)
```

**Comment by Vikram12301** [comment]
Yes it does, the dataset is in my drive and I have given the corresponding paths

**Comment by wwfish** [comment]
I've only ever run tflite-model-maker with datasets stored locally on the colab VM, it might be worth moving your dataset onto the colab machine from your google drive, it may have something to do with the slowing down of access to the dataset via google drive.

**Comment by Vikram12301** [comment]
Ok...
